### ISSUE TITLE
Webui doesn't load

### ISSUE THREAD

**Issue by Mahmoud87** [aptalca/docker-jdownloader2#12]
Hey mate, I am using the docker image you have created and successfully installed it on Rockstor, my problem is am not sure what port jdownloader is listening on. I have noticed you have exposed 2 ports [3389 and 8080] I have tried both of them "localhost:port" but none loading the webui. Am I missing something. I wish you could help me out with this one.

Thanks

**Comment by aptalca** [comment]
Sorry, just noticed this message. You select the port you want to map. Inside the container, it is 8080, but in the docker run/create command, you map port 8080 to whatever port you choose on the host. The readme lists it as XXXX
