### ISSUE TITLE
*** /etc/my_init.d/00_config.sh failed with status 1

### ISSUE THREAD

**Issue by daswars** [aptalca/docker-jdownloader2#2]
*** Killing all processes...
*** Running /etc/my_init.d/00_config.sh...
mv: cannot move '/etc/localtime.dpkg-new' to '/etc/localtime': Device or resource busy
*** /etc/my_init.d/00_config.sh failed with status 1

**Comment by aptalca** [comment]
What platform are you running this on? (Hardware and/or software)

Try removing the following from your run command: `-v /etc/localtime:/etc/localtime:ro` and replace it with the following: `-e TZ="America/New_York"`

You can change the timezone to yours according to the list here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
