### ISSUE TITLE
Memory leak in rdp server ?

### ISSUE THREAD

**Issue by tokyis** [aptalca/docker-jdownloader2#4]
Here is my `top` sorted by memory usage:

      PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                      
    22601 nobody    24   4 8643m 8.4g 6292 S    6 53.6  65:52.67 X11rdp :1 -bs -ac -nolisten tcp -geometry 1280x720 -depth 16 -uds             
    22709 nobody    20   0 9716m 775m 5548 S   12  4.8 152:45.77 /usr/bin/java -Dinstall4j.jvmDir=/usr -Dexe4j.moduleName=/config/jd2/JDownload

It appears the Guacamole / rdp server is hogging quite a bit of memory.
Some details:
-I start the app
-Memory usage is around a 100k
-I connect to the app using chrome without hitting ok, still 100k
-I hit ok, jdownloader shows up, and the X11rdp process starts grabbing memory at a bit less than 1MB/s until I close the connection.

Feels like it's buffering its output as long as there is space in memory, once memory use reaches 75% it seems to stop, is that expected behaviour ?

**Comment by aptalca** [comment]
That is strange. I just checked it on mine. The container running and the webgui open in chrome.

I have two java processes collectively taking up about 9% of the total mem (8GB in my server).

The x11rdp process is using 0.3%

Can you provide more info on your platform (hw/sw), docker version, etc.?

Thanks

**Comment by tokyis** [comment]
I just forced an update and checked, it's still happening.
Here are more info, if you need anything specific, do ask:
```
# docker -v
Docker version 1.7.1, build 786b29d4
# uname -a
Linux BlackHole 4.1.13-unRAID #1 SMP PREEMPT Fri Nov 13 20:26:59 PST 2015 x86_64 Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz GenuineIntel GNU/Linux
```
Motherboard : Asrock C2750D4I
Ram : 16GB ECC
2x 1Gbs aggregated NICs  (mode 802.3ad)
Docker image and appdata user shares on 2x128GB SSD cache pool
Nothing else running apart from plex.

The only thing I did out of the ordinary is `chmod -r +x` from the jd2 directory because jdownloader was auto updating but wasn't setting itself executable. I haven't found a way to disable auto updates.
That was before I forced the container update just now.

**Comment by aptalca** [comment]
A few more questions:
1) What path did you use for the config folder? (/mnt/user or /mnt/cache?)
2) What problem did the permission issue cause? (I never had issues with permissions and auto-updating)
3) You mentioned the problem happening only when the gui is opened in chrome, did you try a different browser?
4) Can you try reinstalling the container but in a different location (preferably /mnt/cache), so let it install from scratch and see if it happens again

**Comment by tokyis** [comment]
1) I use /mnt/user with share set to cache only

2) Well thinking back to it, it probably was caused by me running the New Permissions tool in the webgui, it's supposed to fix and unify permissions on all the disks (some windows backups were giving me trouble), but it strips the exec bit from all the files as well.
Jdownloader was probably running at the time and when I restarted it after an update it failed to restart, I pointed the finger at JDownloader messing up its permissions but it seems the error was between the seat and the keyboard.

3)I tried IE and FF, same thing.

4)Well that did it, I didn't try it before because the last time I tried to backup my settings it failed but this time it worked (probably due to "2)"), at first I thought I would try reinstalling in /mnt/user to see if it was just a problem with the current install and not so much the location, and it worked, it's holding at 0.2%, and I recovered my 6TB download list and settings from the backup just fine.

I can't figure out what went on to end up with rdp behaving that way but I'll blame my noobness with unraid and grovel in apology for wasting your time. ^^

**Comment by aptalca** [comment]
No problem. I'm glad your issue is resolved.

Running the new permissions tool on the docker files is not a good idea. Many containers need custom permissions or ownership on the files. Limetech is trying to centralize the container locations for the next version of unraid. I'll bring it up with them to see if that location can be excluded from the tool.

**Comment by tokyis** [comment]
Yeah, that would be nice, I still run it but on all but the cache disk, most files that would need it are transient and the rest should stay as they are.
On 12 Jan 2016 06:13, aptalca <notifications@github.com> wrote:No problem. I'm glad your issue is resolved.

Running the new permissions tool on the docker files is not a good idea. Many containers need custom permissions or ownership on the files. Limetech is trying to centralize the container locations for the next version of unraid. I'll bring it up with them to see if that location can be excluded from the tool.

**Comment by coolemza** [comment]
i have xubuntu 16.04 with xrdp compiled with xrdp-o-matic and used as terminal server, X11rdp memory using for each user constantly grows until kernel kills it, server have 16gb and 3 user, X11rdp can live about 7-8 days, dunno what can it be..
