### ISSUE TITLE
Copy & paste in link collector not possible

### ISSUE THREAD

**Issue by JamborJan** [aptalca/docker-jdownloader2#5]
I'm running the docker image on a QNAP container station and connect from a Mac book to the web interface.

Everything works fine, except copy and paste. No matter what I do it's not possible to copy and paste a link to the link collector. Any idea what the reason can be?

**Comment by aptalca** [comment]
For the web gui, hit ctrl-alt-shift (all left side)
and a side menu will open. At the top, there is a box, which interacts with the clipboard of the remote app.

Whatever you put into that box will be available in the web gui's clipboard so you can paste it. Whatever you copy within the web gui will be shown in that side box.

But for jdownloader, I strongly recommend using the my.jdownloader.org interface. I use the rdp based web gui for initial set up (to set up the my.jdownloader account), then I use the remote interface.

**Comment by JamborJan** [comment]
Thanks for your help.

My box is not accessible from the outside world, only via VPN. Thats why I cannot use http://my.jdownloader.org
