### ISSUE TITLE
Open access?

### ISSUE THREAD

**Issue by fdbgbgsf** [aptalca/docker-jdownloader2#9]
Am I missing something or is there no login page available for this? The container is accessible to anyone on my network!

**Comment by aptalca** [comment]
Correct. There is no authentication.

If you want to secure it, after setting it up and enabling the my.jdownloader access, you can delete and recreate the container with the same settings except this time without the port mapping, so there will be no vnc gui access (other settings will be preserved as long as you use the same config location). You will still be able to use the my.jdownloader with your account

**Comment by fdbgbgsf** [comment]
Thanks for the info, but I was rather disappointed by the myJDownloader experience previously and can't say it got much better since the last time I used it. Still hoping on a implementation of a basic authentication system.

**Comment by aptalca** [comment]
Well, I'm using someone else's library as a base for the in browser xvnc/xrdp interface, which is based on guacamole. Unfortunately the author seems to have gone awol, but the library still works. I wouldn't hold my breath for new features.

**Comment by fdbgbgsf** [comment]
That's to bad, I've switched to a different container. Thanks for all the effort for the time I've been using it.

**Comment by luckydonald** [comment]
Maybe a settings file would be enough to log in to my.jdownloader:

``` json
{ "password" : "mypasswort", "email" : "email@home.org" }
```

https://board.jdownloader.org/showpost.php?p=345333&postcount=2
